# Generated by Django 3.2.8 on 2021-11-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sang', max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('github', models.CharField(max_length=100)),
                ('bio', models.TextField(null=True)),
                ('avatar', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('project_link1', models.CharField(blank=True, max_length=100)),
                ('project_link2', models.CharField(blank=True, max_length=100)),
                ('project1', models.TextField(null=True)),
                ('project2', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language', models.CharField(default='None', max_length=100)),
                ('tool', models.CharField(max_length=100)),
                ('database', models.CharField(default='None', max_length=100)),
                ('others', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
