# Generated by Django 3.2.9 on 2021-11-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=500)),
                ('avatar', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
            ],
        ),
    ]
