# Generated by Django 3.2.8 on 2021-11-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20211118_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='project',
            new_name='project1',
        ),
        migrations.AddField(
            model_name='profile',
            name='project2',
            field=models.TextField(null=True),
        ),
    ]
