# Generated by Django 3.2.8 on 2021-11-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20211118_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='project_link1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_link2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
