# Generated by Django 3.2.8 on 2021-11-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20211118_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language', models.CharField(default='None', max_length=100)),
                ('tool', models.CharField(default='None', max_length=100)),
                ('database', models.CharField(default='None', max_length=100)),
                ('others', models.CharField(default='None', max_length=100)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile')),
            ],
        ),
    ]
