# Generated by Django 3.2.8 on 2021-11-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='developer',
        ),
    ]
