# Generated by Django 3.2.8 on 2021-11-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_remove_skill_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='tool',
            field=models.CharField(max_length=100),
        ),
    ]
